/**:
  ros__parameters:
    recv_topic: "/vision_recv_data"
    back_target: "/back_target"
    send_topic: "/vision_send_data"
    target_topic: "/target"
    global_position_: "/global_costmap/published_footprint"
    decision_send_topic: "/decision/vision_send_data"
    pursuit_armor_id: "all"
    odom_topic: "/Odometry_transformed"
    hp_threshold: 150.0
    goal_pose_override: "/goal_pose_override"
    area_pub_topic: "/special_areas"
    cmd_vel_remap_topic: "/cmd_vel_remap"
    plan_path_topic: "/Path"
    PID_follower:
      KP: 0.3
      KI: 0.0
      KD: 0.0
      integral: 0.0

    decision_selector: 1

    #设置巡航点

    self_blue:
      goal_points: ["-1.33,0.59","3.51,0.84",]
      supply: ["22.18,2.73"]
      buff_points: ["12.76,2.32","11.61,-5.56",]
      enermy_outpost: ["7.03,-5.02"]
      attack_outpost_point: ["0.47,2.32"]


    self_red:
      goal_points: ["-3.30,-0.20","1.47,-0.30","1.11,2.89",]
      supply: ["-1.72,-5.62"] 
      buff_points: ["8.69,2.72","7.73,-5.21",]
      enermy_outpost: ["13.65,2.31"]
      attack_outpost_point: ["0.47,2.32"]

    attack_outpost: false
    #多边形区域选取为正常的非凸多边形
    special_areas_names: ["R1","R2","B1","B2"]  
    R1:
      type: "both"
      area: "across"
      path_ends: ["9.04,4.61","11.03,4.55",] #如果区域类型为single的时候，第一个为起点
      polygon_ends: 
            ["7.97,4.16","8.61,3.50","9.30,4.21","11.29,4.19","11.32,4.98","8.68,5.10","7.97,4.16",]
    R2:
      type: "both"
      area: "across"
      path_ends: ["6.23,-4.11","7.65,-3.59",] 
      polygon_ends: 
            ["5.92,-3.83","6.17,-4.51","7.94,-3.87","7.65,-3.16","5.92,-3.83",]
    B1:
      type: "both"
      area: "across"
      path_ends: ["12.97,0.88","14.24,1.30",]
      polygon_ends: 
            ["12.69,1.19","12.98,0.43","14.53,1.02","14.28,1.68","12.69,1.19",]
    B2:
      type: "both"
      area: "across"
      path_ends: ["9.61,-7.27","11.65,-7.25",]
      polygon_ends: 
            ["9.31,-6.90","11.17,-6.87","11.84,-6.00","12.74,-6.65","11.95,-7.66","9.22,-7.70","9.31,-6.90",]



